auto-pickup:
  enabled: true
  enabled-in-creative: false
  inventory-full:
    warning:
      enabled: true
      message: '&e&lAP &7Your inventory is full'
      sound: none
  blacklist:
    - CHEST
    - ENDER_CHEST
messages:
  no-permission: '&e&lAP &7You don''t have permission for this'
  auto-pickup-enabled: '&e&lAP &7Auto pickup is now &aenabled'
  auto-pickup-disabled: '&e&lAP &7Auto pickup is now &cdisabled'
  only-players: '&e&lAP &7This command is only for players'